set(SRC_FILES 
    ${CMAKE_CURRENT_LIST_DIR}/main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WifiHelper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Agent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Transport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TCPTransport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Request.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RequestObserver.cpp
)